### PR TITLE
Instacart

### PR DESCRIPTION
**Pull request by anannasreen**

### CODE REVIEW

**Comment by anannasreen** [comment]
_home_anan_Desktop_New%20Folder_Training%20oct_Task13_instacart_index html

**Comment by anannasreen** [comment]
_home_anan_Desktop_New%20Folder_Training%20oct_Task13_instacart_index html (1)

**Comment by anannasreen** [comment]
_home_anan_Desktop_New%20Folder_Training%20oct_Task13_instacart_index html (2)

**Review by APJ-9 — APPROVED** [review]
Spacing issues in `Grocery delivery you can count on ` section 3 cards.
Fix Layout issue

**Pull request merged**
